"""init tables

Revision ID: 005f8478a5cb
Revises: 
Create Date: 2025-10-09 22:21:23.435692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005f8478a5cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('paragraphs_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('modality', sa.String(length=64), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('original_image', 'thumb', 'generated_image', 'other', name='assetkind'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_assets_article_id'), 'assets', ['article_id'], unique=False)
    op.create_table('texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('original_text', 'generated_text_from_image', 'other', name='textkind'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_texts_article_id'), 'texts', ['article_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('image_to_text', 'text_to_image', name='direction'), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('input_asset_id', sa.Integer(), nullable=True),
    sa.Column('input_text_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'skipped', name='runstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['input_text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_article_id'), 'runs', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_article_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_texts_article_id'), table_name='texts')
    op.drop_table('texts')
    op.drop_index(op.f('ix_assets_article_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('models')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
